{
 "title": "System Monitoring Dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "disk Usage",
   "type": "timeseries",
   "description": "To monitor disk usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM ",
   "type": "timeseries",
   "description": "to monitor RAM usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "To monitor CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  }
 ]
}